version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://www.skyquesttinsights.com/api
    restart: unless-stopped
    networks:
      - emlead-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      - PORT=5000
      - FRESHWORKS_API_KEY=${FRESHWORKS_API_KEY}
      - FRESHWORKS_BASE_URL=${FRESHWORKS_BASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGIN=https://www.skyquesttinsights.com
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    networks:
      - emlead-network

networks:
  emlead-network:
    driver: bridge